version: '3.9'

services:

  chronicler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: chronicler
    network_mode: "host"
    command: ["python", "application/custodian_archetypes/chronicler/main.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  companion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sage
    network_mode: "host"
    command: ["python", "application/custodian_archetypes/sage/main.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dispatcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dispatcher
    network_mode: "host"
    command: ["python", "application/dispatcher/dispatcher.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    network_mode: "host"
    command: ["celery", "-A", "application.dispatcher.celery_app", "worker", "--loglevel=info"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: redis
    network_mode: "host"
    ports:
      - "6379:6379"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
