version: '3.9'

services:

  chronicler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: chronicler
    command: ["python", "application/chronicler/main.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - redis
    restart: always

  companion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: companion
    command: ["python", "application/companion/main.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    restart: always

  dispatcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dispatcher
    command: ["python", "application/dispatcher/dispatcher.py"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    restart: always

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "application.dispatcher.celery_app", "worker", "--loglevel=info"]
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
